<?php /***** Process this file with tools/generate.php to produce HTML *****/

page_header('Source code', 'tech-code', null, true);

?>
		<section>
			<dl>
				<!-- Twine -->
				<dt><a href="https://github.com/bbcarchdev/twine/">Twine</a></dt>
				<dd class="desc">Twine is a modular, queue-driven workflow engine for publishing linked open data.</dd>
				<dd><b>Homepage:</b> <a href="/twine/">https://bbcarchdev.github.io/twine</a></dd>
				<dd><b>Repository browser:</b> <a href="https://github.com/bbcarchdev/twine">https://github.com/bbcarchdev/twine</a></dd>
				<dd><b>Language:</b> C</dd>
				<dd><b>Licence:</b> <a href="http://www.apache.org/licenses/LICENSE-2.0">Apache License 2.0</a></dd>

				<!-- Quilt -->
				<dt><a href="https://github.com/bbcarchdev/twine/">Quilt</a></dt>
				<dd class="desc">Quilt is a modular FastCGI application for serving linked open data.</dd>
				<dd><b>Repository browser:</b> <a href="https://github.com/bbcarchdev/quilt">https://github.com/bbcarchdev/quilt</a></dd>
				<dd><b>Language:</b> C</dd>
				<dd><b>Licence:</b> <a href="http://www.apache.org/licenses/LICENSE-2.0">Apache License 2.0</a></dd>

				<!-- libsparqlclient -->
				<dt><a href="https://github.com/bbcarchdev/libsparqlclient/">libsparqlclient</a></dt>
				<dd class="desc">libsparqlclient is a library for performing queries and updates against RDF stores which support SPARQL 1.1.</dd>
				<dd><b>Repository browser:</b> <a href="https://github.com/bbcarchdev/libsparqlclient">https://github.com/bbcarchdev/libsparqlclient</a></dd>
				<dd><b>Language:</b> C</dd>
				<dd><b>Licence:</b> <a href="http://www.apache.org/licenses/LICENSE-2.0">Apache License 2.0</a></dd>

				<!-- liblod -->
				<dt><a href="https://github.com/bbcarchdev/liblod/">liblod</a></dt>
				<dd class="desc">A Linked Open Data (LOD) client library.</dd>
				<dd><b>Repository browser:</b> <a href="https://github.com/bbcarchdev/liblod">https://github.com/bbcarchdev/liblod</a></dd>
				<dd><b>Language:</b> C</dd>
				<dd><b>Licence:</b> <a href="http://www.apache.org/licenses/LICENSE-2.0">Apache License 2.0</a></dd>

				<!-- chrome-lod -->
				<dt><a href="https://github.com/bbcarchdev/chrome-lod/">chrome-lod</a></dt>
				<dd class="desc">Extension for Chrome that checks pages as you browse for the presence of Linked Open Data behind them and reveals the underlying data.</dd>
				<dd><b>Repository browser:</b> <a href="https://github.com/bbcarchdev/chrome-lod">https://github.com/bbcarchdev/chrome-lod</a></dd>
				<dd><b>Language:</b> JavaScript</dd>
				<dd><b>Licence:</b> <a href="https://github.com/bbcarchdev/chrome-lod/blob/master/LICENSE.txt">MIT</a></dd>
				
				<!-- docbook-html5 -->
				<dt><a href="https://github.com/bbcarchdev/docbook-html5/">docbook-html5</a></dt>
				<dd class="desc">XSLT to transform DocBook-XML to (X)HTML5</dd>
				<dd><b>Homepage:</b> <a href="/docbook-html5/">https://bbcarchdev.github.io/docbook-html5/</a></dd>
				<dd><b>Repository browser:</b> <a href="https://github.com/bbcarchdev/docbook-html5">https://github.com/bbcarchdev/docbook-html5</a></dd>
				<dd><b>Language:</b> XSLT</dd>
				<dd><b>Licence:</b> <a href="http://www.apache.org/licenses/LICENSE-2.0">Apache License 2.0</a></dd>
			</dl>
		</section>
<?php
	
page_footer();
	
?>