<?php /***** Process this file with tools/generate.php to produce HTML *****/

page_header('Collection holders', 'collection');

?>
<section>
      <h1>A growing collection of digital assets</h1>
      <p>
        RES is working with a wide variety of collection holders, such as broadcasters, archives, museums, libraries, galleries and publishers, to help them make their digital assets more discoverable. The list of institutions who are publishing their data in a RES-friendly format is growing all the time.
      </p>
      <img class="img_placeholder" src="assets/images/placeholder.png" width="100%"><br><br>
      <p>
        If you’re organisation has a digitised collection, we would love to hear from you. We can show you how publishing your data as <a href="https://en.wikipedia.org/wiki/Linked_open_data">linked open data</a> can increase the visibility of the collections you manage, help you format your data and help you with decision-making about licensing. Add contact details.
      </p>
      <img class="img_placeholder" src="assets/images/placeholder.png" width="100%"><br><br>
      <h2>Make your assets more discoverable</h2>
      <p>
        One major advantage of RES for collection holders is that it democratises asset discovery. By publishing your catalogue as linked open data your assets will be found because of their authenticity, provenance, permanence and because they're appropriately licenced, not because there are lots of links to them on the web. With RES you can control the access to your assets, whereas with search engines the visibility of links to your assets is largely out of your control.
      </p>
      <p>
        With the RES model, a focused collection about a particular niche subject is equal to collections held by huge, world-renowned organisations. 
      </p>
      <p>
        RES is also working with <a href="/res/product">product developers</a> to create digital educational projects using this continually growing free, open-source, openly licenced index of cultural assets.  
      </p>
      <p>
        The Research and Education Space, as its name suggests, is primarily focused on re-use of assets it indexes in the <a href="/res/education">education</a> sector, but you don't have to stop there; once your catalogue is published as linked open data you can use it how and where you like. Websites, apps, connected fridges; it's all open to you.
      </p>
      <p>
        RES currently has indexed data from the following organisations:
      </p>
      <ul>
        <li>National Archives</li>
        <li>Wellcome Trust</li>
        <li>BBC Shakespeare Archive Resource</li>
        <li>Open University</li>
        <li>British Library</li>
        <li>People’s Collection of Wales</li>
        <li>Wikidata </li>
        <li>Europeana</li>
        <li>Natural History Museum</li>
        <li>National Library of Wales</li>
      </ul>
      <p>
      Add explanatory text about what’s in the collection an image and link to each of these collections. We are also working closely with other collection holders, such as:
      </p>
      <ul>
        <li>British Museum</li>
        <li>Imperial War Museums</li>
        <li>Wordsworth Trust</li>
        <li>Ordnance Survey</li>
        <li>British Film Institute </li>
        <li>Horniman Museum</li>
        <li>Science Museum </li>
        <li>Kew Gardens</li>
        <li>British Geological Survey</li>
      </ul>
    </section>

  </section>
  <section class="promo promo--sections">
      <div class="wrapper">      
        <h1>
          Find out more
        </h1>
        <p>
          To find out more, as well as see how to work with us, click the boxes below.
        </p>
      </div>
      <ul class="promo--sections__list">
        <li class="promo--sections__list__item promo--sections__list__item--education">
          <a href="/res/education">
          <h4>Education</h4>
          </a>
        </li>
        <li class="promo--sections__list__item promo--sections__list__item--developers">
          <a href="/res/developers">
          <h4>Product developers</h4>
          </a>
        </li>
      </ul>
  </section>
<?php

page_footer();