<?php /***** Process this file with tools/generate.php to produce HTML *****/

page_header('Collections', 'collection');

?>
<section class="promo">
  <div class="wrapper">
      <h1>A growing collection of digital assets</h1>
      <p>
        RES is working with a wide variety of collection holders, such as broadcasters, archives, museums, libraries, galleries and publishers, to help them make their digital assets more discoverable. The list of institutions who are publishing their data in a RES-friendly format is growing all the time. 
      </p>
      <p>
        If your organisation has a digitised collection, we would love to hear from you at <a href="mailto:RESFeedback@bbc.co.uk">RESFeedback@bbc.co.uk</a>.  We can show you how publishing your data as <a href="http://www.w3.org/standards/semanticweb/data">linked open data</a> can increase the visibility of the collections you manage, help you format your data and help you with decision-making about licensing.
      </p>
      </div>
      <img class="img img--full" src="images/collection2.jpg">
    </section>
<section class="promo">
  <div class="wrapper">
      <h1>Make your assets more discoverable</h1>
      <p>
        One major advantage of RES for collection holders is that it democratises asset discovery. By publishing your catalogue as linked open data, your assets will be found because of their authenticity, provenance, permanence and because they're appropriately licensed, not because there are lots of links to them on the web. With RES you can control the access to your assets, whereas with search engines the visibility of links to your assets is largely out of your control. For instance, with the RES model, a focused collection about a particular niche subject is equal to collections held by huge, world-renowned organisations.
      </p>
      <p>
        RES is also working with <a href="/res/products">product developers</a> to create digital educational projects using this continually growing, free, open-source, openly licensed index of cultural assets.  The Research and Education Space, as its name suggests, is primarily focused on the re-use of assets it indexes in the <a href="/res/education">education sector</a>, but you don't have to stop there; once your catalogue is published as linked open data you can use it how and where you like. Websites, apps; it's all open to you.
      </p>
      <p>Come and join us in RES and make your collections more discoverable and accessible.</p>
      <div>
    </section>
    <section id="institutions" class="promo promo--collection">
      <ul class="promo--collection__list">
        <li class="promo--collection__list__item promo--collection__list__item--british-library"><a href="http://www.bl.uk/">British Library</a></li>
        <li class="promo--collection__list__item promo--collection__list__item--the-national-archives"><a href="http://www.nationalarchives.gov.uk/">The National Archives</a></li>
        <li class="promo--collection__list__item promo--collection__list__item--wikidata"><a href="https://www.wikidata.org/wiki/Wikidata:Main_Page">Wikidata </a></li>
        <li class="promo--collection__list__item promo--collection__list__item--wellcome-trust"><a href="http://www.wellcome.ac.uk/">Wellcome Trust</a></li>
        <li class="promo--collection__list__item promo--collection__list__item--natural-history-museum"><a href="http://www.nhm.ac.uk/">Natural History Museum</a></li>
        <li class="promo--collection__list__item promo--collection__list__item--british-museum"><a href="http://www.britishmuseum.org/">British Museum</a></li>
        <li class="promo--collection__list__item promo--collection__list__item--bbc-shakespeare-archive-resource"><a href="http://shakespeare.ch.bbc.co.uk/">BBC Shakespeare Archive Resource</a></li>
        <li class="promo--collection__list__item promo--collection__list__item--peoples-collection-wales"><a href="http://www.peoplescollection.wales/">People’s Collection of Wales</a></li>
        <li class="promo--collection__list__item promo--collection__list__item--europeana"><a href="http://www.europeana.eu/portal/">Europeana</a></li>
        
      </ul>
    </section>

  </section>
  <section class="promo promo--sections">
      <ul class="promo--sections__list">
        <li class="promo--sections__list__item promo--sections__list__item--education">
          <a href="/res/education">
            <div class="promo--sections__link__inner">
              <h4>Education</h4>
              <p>Lorem ipsum sit amet consecuter</p>
            </div>
          </a>
        </li>
        <li class="promo--sections__list__item promo--sections__list__item--developers">
          <a href="/res/products">
            <div class="promo--sections__link__inner">
              <h4>Products</h4>
              <p>Lorem ipsum sit amet consecuter</p>
            </div>
          </a>
        </li>
      </ul>
  </section>
<?php

page_footer();