<?php /***** Process this file with tools/generate.php to produce HTML *****/

page_header('Products', 'developers');

?>
    <section>
      <h1>Open platform to build new products</h1>
      <p>
        The RES project provides an open platform built by the BBC, which means anyone can make use of the index data and interpret it in order to build useful products and services aimed at UK education and research. We are already working with ambitious and innovative product developers to create digital educational experiences that will inspire learners, teachers and researchers by using applications powered by the RES platform. We’d like to hear more ideas from you, so please get in touch to find out how you can incorporate RES into your products at <a href="mailto:resfeedback@bbc.co.uk">RESFeedback@bbc.co.uk</a>.
      </p>
    </section>
    <section class="promo promo--tech">
      <div class="wrapper">
        <h1>Technical guides</h1>
        <p>
          You will find guidance and documentation for application developers, data contributors and users of RES in Technology. RES offers a free, openly licenced index of cultural assets from some of the world's leading cultural institutions. Images, video, TV and radio programmes, podcasts, text, pre-formatted teaching materials, are all  being indexed by RES.  Plug RES into your product and you will instantly add value to your product and for your audeince.
        </p>
        <p><a class="promo--tech__btn" href="/res/tech"><span>View technical guides</span></a></p>
      </div>
    </section>
    <section>
      <p>
        Our aim is to enable the production of products so that teachers looking to illustrate lesson plans will find a rich, carefully organised, properly licenced collection of relevant material. Students wanting to illustrate their coursework will find it incredibly easy to find the exact photo or video they need. Academics will be able to engage with specialist audio-visual resources that have been hitherto inaccessible.
      </p>
    </section>
    <section class="promo promo--powered">
      <div class="wrapper">
        <img class="promo--powered__img" src="images/powered-by-res.png">
        <p>                                           
          Although we don’t always know who is using a product powered by RES, we’ve worked with the following companies to include aspects of the RES project in their products. Get in touch at <a href="mailto:resfeedback@bbc.co.uk">RESFeedback@bbc.co.uk</a> if you’re powered by RES and want to be included here. 
        </p>
      </div>
    </section>
    <section class="promo promo--collaboration">
      <div class="wrapper">
        <p>
          In 2014, BBC Connected Studio invited developers, digital agencies and start-ups to help build prototypes for the Research and Education Space platform.  The following three prototypes were commissioned:
        </p>
        <ul class="promo--collaboration__list">
          <li class="promo--collaboration__list__item promo--collaboration__list__item--touchpress">Soundpools – developed by Touchpress, uses an immersive audio experience to tell a story.</li>
          <li class="promo--collaboration__list__item promo--collaboration__list__item--gooii">RES Builder – developed by Gooii, allows the user to highlight text from any document, extract concepts from that text using the RES platform, and display all related media to the user.</li>
          <li class="promo--collaboration__list__item promo--collaboration__list__item--amplify">Tunnels – developed by Amplify, uses a creative timeline of selected clips of archival media to explore a topic.</li>
        </ul>
      </div>
  </section>
  <section class="promo promo--sections">
      <div class="wrapper">      
        <h1>
          Find out more
        </h1>
        <p>
          To find out more, as well as see how to work with us, click the boxes below.
        </p>
      </div>
      <ul class="promo--sections__list">
        <li class="promo--sections__list__item promo--sections__list__item--education">
          <a href="/res/education">
          <h4>Education</h4>
          </a>
        </li>
        <li class="promo--sections__list__item promo--sections__list__item--collection">
          <a href="/res/collection">
          <h4>Collections</h4>
          </a>
        </li>
      </ul>
    </section>
<?php

page_footer();
