<?php /***** Process this file with tools/generate.php to produce HTML *****/

page_header('Project developers');

?>
    <section>
      <h1>Open platform to build new products</h1>
      <p>
        RES is an open platform built by the BBC, which means anyone can make use of the index and interpret the data in order to build useful products and services aimed at UK education and research. We are already working with ambitious and innovative product developers to create digital educational experiences that will inspire learners, teachers and researchers by using applications powered by the RES platform. We’d like to hear more ideas from you, so please get in touch to find out how you can incorporate RES into your products.
      </p>
    </section>
    <section class="promo promo--tech">
      <h1>Trusted and permanently available</h1>
      <p>
        You will find guidance and documentation for application developers, data contributors and users of RES in Technology. RES offers a free, open-source, openly licenced index of cultural assets from some of the world's leading cultural institutions. Images, video, TV and radio programmes, podcasts, text, pre-formatted teaching materials, all are being indexed by RES. Plug RES into your product and you will instantly add value to your clients and hence to your product.
      </p>
      <p><a class="promo--tech__btn" href="/res/tech">Technical guides</a></p>
    </section>
    <section>
      <p>
        Teachers looking to illustrate lesson plans will find a rich, carefully organised, properly licenced collection of relevant material. Students wanting to illustrate their coursework will find it incredibly easy to find the exact photo or video they need.
      </p>
      <p>                                           
        In 2014, BBC Connected Studio invited developers, digital agencies and start-ups to help build prototypes for the Research and Education Space platform.  The following three prototypes were commissioned: 
      </p>
      <ul>
        <li>oundpools – developed by Touchpress, which uses an immersive audio experience to tell a story. </li>
        <li>Tunnels – developed by Amplify, which uses a creative timeline of selected clips of archival media to explore a topic.</li>
        <li>Media Match (RES Builder) – developed by GUI, which allows the user to highlight some text from any document, the tool then extracts concepts from that text using the RES platform to find matches to the media, imports what it finds and lists in a menu.</li>
      </ul>
      <p></p>
      <p>
        Although we don’t always know who is using a product powered by RES, we’ve worked with the following companies to include aspects of the RES project in their products. Get in touch if you’re powered by RES and want to be included here. 
      </p>
  </section>
  <section class="promo promo--sections">
      <div class="wrapper">      
        <h1>
          Find out more
        </h1>
        <p>
          To find out more, as well as see how to work with us, click the boxes below.
        </p>
      </div>
      <ul class="promo--sections__list">
        <li class="promo--sections__list__item promo--sections__list__item--education">
          <a href="/res/education">
          <h4>Education</h4>
          </a>
        </li>
        <li class="promo--sections__list__item promo--sections__list__item--collection">
          <a href="/res/collection">
          <h4>Collection holders</h4>
          </a>
        </li>
      </ul>
    </section>
<?php

page_footer();
