<?php /***** Process this file with tools/generate.php to produce HTML *****/

page_header('Education', 'education');

?>
    <section>
      <h1>Access to reliable online resources</h1>
      <p>
        We know that finding reliable online resources is important for academics, students and teachers in all subject areas and at all levels. Although the Internet offers a lot of material, it’s sometimes hard to find what you’re looking for and you can’t always rely on it being there. .  
      </p>
      <p>
        The <a href="/res">RES project</a> is working with some of our largest public institutions like the British Library, the National Archives, the Wellcome Trust, the Natural History Museum and the BBC, to make their content available to those in UK education.  We are also working with individuals and companies that build the products and services used in education and introducing them to the wealth of material that is being pulled together by the RES platform. As a professional in education you will not be able to use the RES platform directly, instead you can access it via third party <a href="/res/developers">products and services</a>.
      </p>
      <h2>
        Licensed for educational use
      </h2>
      <img class="img img--half" src="images/developer3.jpg">
      <p>
        The RES initiative was launched to make lessons, lectures and learning more interesting, varied, colourful and informative, to enrich teaching across different levels and subjects and to support research at all levels.  
      </p>
      <p>
        RES offers a free, openly licenced index of cultural assets from some of the world's leading cultural institutions. Images, video, TV and radio programmes, podcasts, text, pre-formatted teaching materials, are all being indexed by RES.  The information about rights is included with the assets. Where a particular resource requires a specific licence, such as the ERA licence that permits use of off-air broadcasts, this will be indicated.
      </p>
      <h2>
        Suitable for all subjects and levels 
      </h2>
      <img class="img img--half" src="images/education2.jpg">
      <p>
        RES will include a wide range of material relevant to education and research at all levels, from primary schools to post-doctoral research. Teachers looking to illustrate lesson plans will find a rich, carefully organised, properly licenced collection of relevant material. Students wanting to illustrate their coursework will find it incredibly easy to find the exact photo or video they need. Academics will be able to engage with specialist audio-visual resources that have been hitherto inaccessible. 
      </p>
      <h2>
        An open and growing resource
      </h2>
      <p>
        The RES <a href="/res/tech">RES platform</a> is an open platform that anyone can use, and as the catalogue starts to grow, we will be working with <a href="/res/developers#companies">companies</a> who can build innovative educational resources around it.  
      </p>
      <p>
        The RES platform is open and free to use, but products, tools and services built on it may charge. RES makes resources more discoverable, but existing licensing schemes remain in effect.
      </p>
      <p>
        To tell us how we can help make RES work for you, please contact us at <a href="mailto:resfeedback@bbc.co.uk">resfeedback@bbc.co.uk</a>
      </p>
    </section>

  </section>
  <section class="promo promo--sections">
      <div class="wrapper">      
        <h1>
          Find out more
        </h1>
        <p>
          To find out more, as well as see how to work with us, click the boxes below.
        </p>
      </div>
      <ul class="promo--sections__list">
        <li class="promo--sections__list__item promo--sections__list__item--collection">
          <a href="/res/collection">
          <h4>Collection holders</h4>
          </a>
        </li>
        <li class="promo--sections__list__item promo--sections__list__item--developers">
          <a href="/res/developers">
          <h4>Product developers</h4>
          </a>
        </li>
      </ul>
  </section>
<?php

page_footer();
