<?php /***** Process this file with tools/generate.php to produce HTML *****/

page_header('Education', 'education');

?>
    <section class="promo">
        <div class="wrapper">
      <h1>Access to reliable online resources</h1>
      <p>
        We know that finding reliable online resources is important for academics, students and teachers in all subject areas and at all levels. Although the Internet offers a lot of material, it’s sometimes hard to find what you’re looking for and you can’t always rely on it being there.
      </p>
      <p>
        The Research and Education Space (<a href="/res#introduction">RES</a>) is working with world class institutions, like The British Museum, British Library, The National Archives, Wellcome Trust, Natural History Museum and the BBC, to make their content available to those in UK education. We are also working with individuals and companies that build the products and services used in education and introducing them to the wealth of material that is being pulled together by the RES platform. As a professional in education you will not be able to use the RES platform directly, instead you can access it via third party <a href="/res/products">products and services</a>.
      </p>    
    </div>
    </section> 
      <section class="promo promo--education">
        <div class="wrapper">
      <h1>
        Licensed for educational use
      </h1>
      <p>
        The RES initiative was launched to make lessons, lectures and learning more interesting, varied, colourful and informative, to enrich teaching across different levels and subjects and to support research at all levels.  
      </p>    
      <p>
        RES offers a free, openly licensed index of cultural assets from some of the world's leading cultural institutions. Images, TV and radio programmes, podcasts, documents, text, pre-formatted teaching materials, and more are all being indexed by RES.  The information about rights is included with the assets. Where a particular resource requires a specific licence, such as the ERA licence that permits use of off-air broadcasts, this will be indicated.
      </p>
    </div>
    </section>
    <section class="promo">
        <div class="wrapper">
      <h1>
        Suitable for all subjects and levels 
      </h1>
      <img class="img img--full" src="images/education1.jpg">
      <p>
        RES includes a wide range of material relevant to education and research at all levels, from primary schools to post-doctoral research. Teachers looking to illustrate lesson plans will find a rich, carefully organised, and properly licensed collection of relevant material. Students wanting to illustrate their coursework will find it incredibly easy to find the exact photo or video they need. Academics will be able to engage with specialist audio-visual resources that have been hitherto inaccessible. 
      </p>
      <p>
        BBC assets currently available for use on the RES platform include the BBC Shakespeare Archive Resource, over 45,000 images from the BBC library, around 1,600 classroom clips from BBC Teach and 1,500 media items from BBC RemArc (a Reminiscence Archive developed to benefit dementia patients and their carers). In addition data from cultural and heritage institutions such as the Wellcome Collection, British Library Discovering Literature collection, Natural History Museum, Europeana  and Ordnance Survey are being ingested and indexed by the RES platform.
      </p>
      <h1>Teaching Shakespeare</h1>
      <p>Watch this film to see how the BBC Shakespeare collection is being used in education.</p>
    <section class="smp"> 
      <div id="mediaPlayerWrapper">
        <iframe id="mediaPlayer" style="height: 960px; width: 549px;" src="https://play.bbcarchdev.net/p03tx3xm/player"></iframe>
      </div>
    </section><br/><br/>
      <h1>
        An open and growing resource
      </h1>
      <img class="img img--full" src="images/education2.jpg">
      <p>
        The <a href="/res/developers">RES platform</a> is an open platform that anyone can use, and as the catalogue grows, we will continue to work with developers who can build innovative educational resources on it.  
      </p>
      <p>
        RES content will be available via third party portals such as Learning on Screen’s <a href="http://bufvc.ac.uk/tvandradio/bob">BoB</a>, Planet eStream’s <a href="http://www.planetestream.co.uk/connect.aspx">Connect</a> service, ClickView, Imagen, VLEs and other learning tools powered by RES.
      </p>
      <p>
        To tell us how we can help make RES work for you, please contact us at: <a href="mailto:resfeedback@bbc.co.uk">RESFeedback@bbc.co.uk</a>
      </p>
    </div>
    </section>
  </section>
  <section class="promo promo--sections">
      <ul class="promo--sections__list">
        <li class="promo--sections__list__item promo--sections__list__item--collection">
          <a href="/res/collections">
            <div class="promo--sections__link__inner">
              <h4>Collections</h4>
              <p>Information for curators of digital collections</p>
            </div>
          </a>
        </li>
        <li class="promo--sections__list__item promo--sections__list__item--developers">
          <a href="/res/products">
            <div class="promo--sections__link__inner">
              <h4>Products</h4>
              <p>Information for product developers</p>
            </div>
          </a>
        </li>
      </ul>
  </section>
<?php

page_footer();
