<?php /***** Process this file with tools/generate.php to produce HTML *****/

page_header('Education');

?>
    <section>
      <h1>Access to reliable online resources</h1>
      <p>
        You’ve told us that finding online resources you can rely on is important for academics, students and teachers in all subject areas and at all levels. Although the Internet offers a lot of material, it’s sometimes hard to find what you’re looking for and you can’t always rely on it being there.  
      </p>
      <p>
        The <a href="index.html">RES project</a> is working with the individuals and companies that build products and services used in education, to introduce them to the wealth of material which is being pulled together by the RES platform. This includes the catalogues and the collections they describe from some of our largest public institutions like the British Library, the National Archives, and the BBC. As a professional in education you will not be able to use the RES platform directly, but instead you can access it via third party <a href="/res/developers">products and services</a>.
      </p>
      <h2>
        Licensed for educational use
      </h2>
      <p>
        The RES initiative was launched to make lessons, lectures and learning more interesting, varied, colourful and informative, to enrich teaching across different levels and subjects and to support research at all levels. It aims to be clear about what you are allowed to do with the material you find.  
      </p>
      <p>
        RES searches for materials that have been licensed for educational use in the UK or are out of copyright or otherwise available for teaching and research purposes, and the information about rights will be held in the RES catalogue. Where a particular resource requires a specific licence, such as the ERA licence that permits use of off-air broadcasts, this will be indicated.
      </p>
      IMAGE<img class="img_placeholder" src="assets/images/placeholder.png"><br><br>
      <h2>
        Suitable for all subjects and levels 

      </h2>
      <p>
        RES will include a wide range of material relevant to education and research at all levels, from primary schools to post-doctoral research. RES will index materials that have been licensed for a wide variety of creative, imaginative and innovative educational uses. Many will be available to be adapted for learners at all levels and across every curriculum subject and topic. 
      </p>
      IMAGE<img class="img_placeholder" src="assets/images/placeholder.png" width="100%"><br><br>
      <h2>
        An open, free to use and growing resource
      </h2>
      <p>
        The RES platform already exists and the catalogue is starting to grow. We are working with <a href="/res/developers#companies">companies</a> who build a range of educational tools who want to build resources around it.  As the <a href="/res/tech">RES platform</a> is an open platform anyone can use it. 
        The RES platform is open and free to use, but products, tools and services built on it may charge. RES makes resources more discoverable, but existing licensing schemes remain in effect. 
      </p>
    </section>

  </section>
  <section class="promo promo--sections">
      <div class="wrapper">      
        <h1>
          Find out more
        </h1>
        <p>
          To find out more, as well as see how to work with us, click the boxes below.
        </p>
      </div>
      <ul class="promo--sections__list">
        <li class="promo--sections__list__item promo--sections__list__item--collection">
          <a href="/res/collection">
          <h4>Collection holders</h4>
          </a>
        </li>
        <li class="promo--sections__list__item promo--sections__list__item--developers">
          <a href="/res/developers">
          <h4>Product developers</h4>
          </a>
        </li>
      </ul>
  </section>
<?php

page_footer();
