<?php /***** Process this file with tools/generate.php to produce HTML *****/

page_header('FAQ');

?>
    <section class="promo">
      <div class="wrapper">
      <h1>
        What is the Research and Education Space (RES)?
      </h1>
      <p>
        The Research and Education Space (RES) is a partnership project between <a href="https://www.jisc.ac.uk/">Jisc</a>, the <a href="http://bufvc.ac.uk/">British Universities Film &amp; Video Council (BUFVC)</a> and the <a href="https://www.bbc.co.uk/">BBC</a> that aims to make it easier for teachers, students and academics to discover, access and use material held in the public collections of broadcasters, museums, libraries, galleries and publishers.
      </p>
      <h1>
        The RES initiative comprises:
      </h1>
      <ul>
        <li>
          The <a href="/res/tech">RES platform</a> – an open platform built by the BBC, which organises and indexes the catalogues of publicly-held archives.
        </li>
        <li>
          A <a href="/res/collection">collaboration</a> - to work with public sector organisations, such as British Museum, British Library, National Archives, , Europeana, the Wellcome Trust, the BBC and the Tate galleries, to release their catalogues and the assets they describe, in the form of linked open data, to assist in the discovery of these assets.
        </li>
        <li>
          An <a href="/res/developers">ambition</a> - to stimulate public and private companies to build products powered by RES for teachers, learners and academics, to help them access the data and collections. 
        </li>
      </ul>
      <h1>
      How does RES work?
      </h1>
      <p>
      The RES platform is a technical stack which collects, indexes and organises rich structured data about those archive collections published as Linked Open Data (LOD) on the Web. The collected data is organised around the people, places, events, concepts and things related to the items in the archive collections - and, if the archive assets themselves are available in digital form, that data includes the information on how to access them, all in a consistent machine-readable form. The RES platform has a powerful API to ensure applications can make use of the index data, along with the source data, to make those collections accessible and meaningful.
      </p>
      <h1>
      I want to contribute data to RES, how can I do this?
      </h1>
      <p>
      <a href="/inside-acropolis/#publishers">This section</a> describes how a collection-holder can publish their data in a form which can be indexed by the RES platform and used by applications, and how an application developer can make use of the index and interpret the source data in order to present it to end-users in a useful way. Further guidance and documentation for data contributors, application developers and users of RES tools can be found on our <a href="/res/tech">Technical pages</a>.
       </p>
      <h1>
      What is Linked Open Data?
      </h1>
      <p>
      Linked Data is a way of expressing information in a way that can be understood by machines, using the same mechanisms that drive the Web we all use today. Linked Open Data, means that this information is not only available, but can be openly reused without having to ask for specific permissions and so on.
      </p>
      <h1>
      Who is making their catalogues available through RES?
      </h1>
      <p>
      RES is working with a wide variety of collection holders, such as broadcasters, archives, museums, libraries, galleries and publishers, to help them make their digital assets more discoverable. The <a href="/res/collection">list</a> of institutions who are publishing their data in a RES-friendly format is growing all the time. 
      </p>
      <h1>
      I would like to build a product on the RES platform, how can I do this?
      </h1>
      <p>
      The RES platform is open so anybody can use it to build a product or service, providing they adhere to the terms of use for the data and the assets referenced by that data.
      </p>
      <h1>
      Why should I use RES?
      </h1>
      <p>
      The aim is for RES to make study, research, lessons and learning more interesting, varied, colourful and informative, to enrich teaching across different levels and subjects and to support research at all levels. It offers a reliable, openly licenced index of cultural assets from some of the world's leading cultural institutions. There is no charge to build on the RES platform.
      </p>
      <h1>
      What types of material will be available for use?
      </h1>
      <p>
      Examples include film, video, audio, photos and images, commercial music, sheet music and historical documents.
      </p>
      <h1>
      Will RES have material for all levels of research, study and teaching?
      </h1>
      <p>
      Yes. RES will include links to material relevant to education and research at all levels, from primary schools to post-doctoral research. RES will index materials that have been licensed for a wide variety of creative, imaginative and innovative educational uses. Many will be available to be adapted for learners at all levels and across every curriculum subject and topic.
      </p>
      <h1>
      How will I know if I have the rights to use the content in my lessons?
      </h1>
      <p>
      The information about rights will be included with the assets. Where a particular resource requires a specific licence, such as the ERA licence that permits use of off-air broadcasts in formal education, this will be indicated.
      </p>
      <h1>
      When will RES be available?
      </h1>
      <p>
      The RES platform already exists and the catalogue is starting to grow, and we are developing a range of tools to be used by software companies and educational publishers who want to build resources around it. 
      </p>
      <h1>
      Will there be a cost for using RES? Do I need to subscribe or buy a membership?
      </h1>
      <p>
      The RES platform is free to use, but products, tools and services built on top of it may be commercially available. RES does not affect the licensing of the actual resources in any way, but simply makes them more discoverable, so existing licensing schemes are unchanged.
      </p>
      <h1>
      Will I be allowed to stream, download and make clips of audio and video?
      </h1>
      <p>
      The details of what uses are permitted for a particular asset indexed by the RES platform are entirely up to the rights holder and will depend on the licence terms and conditions. RES does not store any materials itself, but simply makes them more discoverable, so existing licensing schemes are unchanged.
      </p>
      <h1>
      What is the BBC’s involvement in RES?
      </h1>
      <p>
      The BBC has built the RES platform through which online educational resources can be discovered and used. Because it is open, it can be built on by anyone, so the range of products that can be built on it is huge.  RES is not a new BBC product, service or website.
      </p>
      <h1>
      Who is behind RES?
      </h1>
      <p>
      RES is a partnership project between Jisc, the British Universities Film & Video Council (BUFVC) and the BBC.
      </p>
      <h1>
      How do I contact the RES project?
      </h1>
      <p>
      The RES project team can be contacted by email at <a href="mailto:resfeedback@bbc.co.uk">RESFeedback@bbc.co.uk</a>
      </p>
      <h1>
      What is the BBC Shakespeare Archive Resource?
      </h1>
      <p>
      The <a href="http://shakespeare.ch.bbc.co.uk/">BBC Shakespeare Archive Resource</a> provides schools, colleges and universities across the UK with online access to the BBC’s Shakespeare collection of hundreds of television and radio programmes, including performances, sonnets, documentaries, interviews and more, dating from the 1950s. It also includes over 1000 photographs of classic Shakespeare productions and performers.
      </p>
      <h1>
      How long is RES funded for?
      </h1>
      <h1>
      How do I find out if my educational product is using RES?
      </h1>
      <h1> 
      How do I find out what collections I can access through the RES platform?
      </h1>
    </div>
    </section>

  </section>
  <section class="promo promo--sections">
      <div class="wrapper">      
        <h1>
          Find out more
        </h1>
        <p>
          To find out more, as well as see how to work with us, click the boxes below.
        </p>
      </div>
      <ul class="promo--sections__list">
        <li class="promo--sections__list__item promo--sections__list__item--education">
          <a href="education.html">
          <h4>Education</h4>
          </a>
        </li>
        <li class="promo--sections__list__item promo--sections__list__item--developers">
          <a href="developers.html">
          <h4>Product developers</h4>
          </a>
        </li>
      </ul>
  </section>
<?php

page_footer();