<?php /***** Process this file with tools/generate.php to produce HTML *****/

page_header('FAQ', 'faq');

?>      
    <nav class="toc">
      <h1>
        Table of contents
      </h1>
      <ul>
        <li><a href="#faq-what">What is the Research and Education Space?</a></li>
        <li><a href="#faq-how">How does RES work?</a></li>
        <li><a href="#faq-contribute">I want to contribute data to RES, how can I do this?</a></li>
        <li><a href="#faq-lod">What is Linked Open Data?</a></li>
        <li><a href="#faq-catalogues">Who is making their catalogues available through RES?</a></li>
        <li><a href="#faq-products">I would like to build a product on the RES platform.</a></li>
        <li><a href="#faq-build">How can I build a product on the RES platform?</a></li>
        <li><a href="#faq-why">Why should I use RES?</a></li>
        <li><a href="#faq-material">What types of material will be available for use?</a></li>
        <li><a href="#faq-levels">Will RES have material for all levels of research, study and teaching?</a></li>
        <li><a href="#faq-rights">How will I know if I have the rights to use the content in my lessons?</a></li>
        <li><a href="#faq-available">When will RES be available?</a></li>
        <li><a href="#faq-cost">Will there be a cost for using RES? Do I need to subscribe or buy a membership?</a></li>
        <li><a href="#faq-resources">Will I be allowed to stream, download and make clips of audio and video?</a></li>
        <li><a href="#faq-partnership">Who is behind RES?</a></li>
        <li><a href="#faq-bbc">What is the BBC’s involvement in RES?</a></li>
        <li><a href="#faq-contact">How do I contact the RES project?</a></li>
        <li><a href="#faq-shakespeare">What is the BBC Shakespeare Archive Resource?</a></li>
        <li><a href="#faq-future">What is the future of RES??</a></li>
        <li><a href="#faq-archive">How is the BBC making its archive available?</a></li>
        <li><a href="#faq-licence">Who needs an ERA licence?</a></li>
      </ul>
    </nav>
    <section >
      <div class="wrapper">

      <h2 id="faq-what">
        What is the Research and Education Space (RES)?
      </h2>
      <p>
        The Research and Education Space (RES) is a partnership project between <a href="https://www.jisc.ac.uk/">Jisc</a>, the <a href="http://bufvc.ac.uk/">British Universities Film &amp; Video Council (BUFVC)</a> and the <a href="https://www.bbc.co.uk/">BBC</a> that aims to make it easier for teachers, students and academics to discover, access and use material held in the public collections of broadcasters, museums, libraries, galleries and publishers.
      </p>
      <h3>
        The RES initiative comprises:
      </h3>
      <ul>
        <li>
          The <a href="/res/products">RES platform</a> – an open platform built by the BBC, which organises and indexes the catalogues of publicly-held archives.
        </li>
        <li>
          A <a href="/res/collections">collaboration</a> - working with public sector organisations, such as The British Museum, British Library, The National Archives, , Europeana, Wellcome Trust, the BBC and Tate galleries, to release their catalogues and the assets they describe, in the form of <a href="http://5stardata.info/en/">linked open data</a>, to assist in the discovery of these assets.
        </li>
        <li>
          An <a href="/res/products">ambition</a> - to stimulate public and private companies to build products powered by RES for teachers, learners and academics, to help them access the data and collections. 
        </li>
      </ul>
      <h2 id="faq-how">
      How does RES work?
      </h2>
      <p>
      The RES platform is an open source software stack which collects, indexes and organises rich structured data about those archive collections published as Linked Open Data (LOD) on the Web. The collected data is organised around the people, places, events, concepts and things related to the items in the archive <a href="/res/collections">collections</a>. If the archive assets themselves are available in digital form, that data includes the information on how to access them, all in a consistent, machine-readable form. The RES platform has a powerful API to ensure applications can make use of the index data, along with the source data, to make those collections accessible and meaningful.
      </p>
      <h2 id="faq-contribute">
      I want to contribute data to RES, how can I do this?
      </h2>
      <p>
      <a href="/inside-acropolis/#publishers">This section</a> of the developer guide describes how a curator of a digital collection can publish their data in a form which can be indexed by the RES platform and used by applications, and how an application developer can make use of the index and interpret the source data in order to present it to end-users in a useful way. Further guidance and documentation for data contributors, application developers and users of RES tools can be found on our <a href="/res/developers">Technical pages</a>.
       </p>
      <h2 id="faq-lod">
      What is Linked Open Data?
      </h2>
      <p>
      <a href="https://www.w3.org/DesignIssues/LinkedData.html">Linked Data</a> is a way of expressing information in a way that can be understood by machines, using the same mechanisms that drive the Web we all use today. Linked Open Data means that this information is not only available, but can be openly reused without having to ask for specific permissions and so on.
      </p>
      <h2 id="faq-catalogues">
      Who is making their catalogues available through RES?
      </h2>
      <p>
      RES is working with a wide variety of collection holders, such as broadcasters, archives, museums, libraries, galleries and publishers, to help them make their digital assets more discoverable. The list of <a href="/res/collections#institutions">institutions</a> who are publishing their data in a RES-friendly format is growing all the time. 
      </p>
      <h2 id="faq-products">
      I would like to build a product on the RES platform.
      </h2>
      <p>
      The RES platform is open so anybody can use it to build a product or service, providing they adhere to the terms of use for the data and the assets referenced by that data.
      </p>
      <h2 id="faq-build">
      How can I build a product on the RES platform?
      </h2>
      <p>
      For more information about how to build a product on the RES platform please refer to the <a href="/res/developers">Developer Resources</a>. 
      </p>
      <h2 id="faq-why">
      Why should I use RES?
      </h2>
      <p>
      The aim is for RES to make study, research, lessons and learning more interesting, varied, colourful and informative, to enrich teaching across different levels and subjects and to support research at all levels. It offers a reliable, openly licensed index of cultural assets from some of the world's leading cultural institutions. There is no charge to build on the RES platform.
      </p>
      <h2 id="faq-material">
      What types of material will be available for use?
      </h2>
      <p>
      Examples include video, audio, photos and images, commercial music, sheet music and historical documents.
      </p>
      <h2 id="faq-levels">
      Will RES have material for all levels of research, study and teaching?
      </h2>
      <p>
      Yes. RES will include links to material relevant to education and research at all levels, from primary schools to post-doctoral research. RES will index materials that have been licensed for a wide variety of creative, imaginative and innovative educational uses. Many will be available to be adapted for learners at all levels and across every curriculum subject and topic.
      </p>
      <h2 id="faq-rights">
      How will I know if I have the rights to use the content in my lessons?
      </h2>
      <p>
      The information about rights will be included with the assets. Where a particular resource requires a specific licence, such as the ERA licence that permits use of off-air broadcasts in formal education, this will be indicated.
      </p>
      <h2 id="faq-available">
      When will RES be available?
      </h2>
      <p>
      The RES platform already exists and the catalogue is starting to grow, and we are developing a range of tools to be used by software companies and educational publishers who want to build resources around it. 
      </p>
      <h2 id="faq-cost">
      Will there be a cost for using RES? Do I need to subscribe or buy a membership?
      </h2>
      <p>
      The RES platform is free to use, but products, tools and services built on top of it may be commercially available. RES does not affect the licensing of the actual resources in any way, but simply makes them more discoverable, so existing licensing schemes are unchanged.
      </p>
      <h2 id="faq-resources">
      Will I be allowed to stream, download and make clips of audio and video?
      </h2>
      <p>
      The details of what uses are permitted for a particular asset indexed by the RES platform are entirely up to the rights holder and will depend on the licence terms and conditions. RES does not store any materials itself, but simply makes them more discoverable, so existing licensing schemes are unchanged.
      </p>
      <h2 id="faq-partnership">
      Who is behind RES?
      </h2>
      <p>
      RES is a partnership project between Jisc, the British Universities Film & Video Council (BUFVC) and the BBC.
      </p>
      <h2 id="faq-bbc">
      What is the BBC’s involvement in RES?
      </h2>
      <p>
      The BBC has built the RES platform through which online educational resources can be discovered and used. Because it is open, it can be built on by anyone, so the range of products that can be built on it is huge.  RES is not a new BBC product, service or website.
      </p>
      <h2 id="faq-contact">
      How do I contact the RES project?
      </h2>
      <p>
      The RES project team can be contacted at <a href="mailto:resfeedback@bbc.co.uk">RESFeedback@bbc.co.uk</a>
      </p>
      <h2 id="faq-shakespeare">
      What is the BBC Shakespeare Archive Resource?
      </h2>
      <p>
      The <a href="http://shakespeare.ch.bbc.co.uk/">BBC Shakespeare Archive Resource</a> provides schools, colleges and universities across the UK with online access to the BBC’s Shakespeare collection of hundreds of television and radio programmes. These include performances, sonnets, documentaries, interviews and more, dating from the 1950s. 
      </p>
      <h2 id="faq-future">
      What is the future of RES?
      </h2>
      <p>
      Over 4 years, the BBC is working in partnership with the BUFVC and Jisc to deliver and launch the Research and Education Space. It is envisaged that, over time, this new service will continue to develop and grow as more content is added and products powered by RES are built on the platform.   
      </p>
      <h2 id="faq-archive">
      How is the BBC making its archive available?
      </h2>
      <p>
      The BBC is committed to making as much of its archive as possible available to those in formal UK learning, from schools to universities. Access to the BBC programme archive is possible under various permissions; copyright in programmes has expired; programmes are cleared with right’s holders for various uses; and under an exemption in the 1988 Copyright, Designs and Patents Act, which entitles those in formal UK education to use TV and radio programmes captured off-air in teaching and research. This is managed by the <a href="http://www.era.org.uk/">ERA Licensing Scheme</a>.  
      </p>
      <h2 id="faq-licence">
      Who needs an ERA licence?
      </h2>
      <p>
      You will require an <a href="http://www.era.org.uk/">ERA licence</a> if you wish to use material sourced from broadcasts for teaching resources. As part of the RES project, over 900,000 BBC TV and radio programmes dating back to 2007 are now available on the BUFVC’s BoB and Planet eStream’s Connect services, for use by ERA licensed educational establishments.
      </p>
    </div>
    </section>

    <section class="promo promo--sections">
      <ul class="promo--sections__list">
        <li class="promo--sections__list__item promo--sections__list__item--education">
          <a class="promo--sections__link" href="/res/education">
            <div class="promo--sections__link__inner">
              <h4>Education</h4>
              <p>Information for the Education sector</p>
            </div>
          </a>
        </li>
        <li class="promo--sections__list__item promo--sections__list__item--collection">
          <a class="promo--sections__link" href="/res/collections">
            <div class="promo--sections__link__inner">
              <h4>Collections</h4>
              <p>Information for curators of digital collections</p>
            </div>
          </a>
        </li>
        <li class="promo--sections__list__item promo--sections__list__item--developers">
          <a class="promo--sections__link" href="/res/products">
            <div class="promo--sections__link__inner">
              <h4>Products</h4>
              <p>Information for product developers</p>
            </div>
          </a>
        </li>
      </ul>
    </section>
<?php

page_footer();