<?php /***** Process this file with tools/generate.php to produce HTML *****/

page_header('FAQ');

?>
    <section>
      <h1>FAQ</h1>
      <p>
      </p>
    </section>

  </section>
  <section class="promo promo--sections">
      <div class="wrapper">      
        <h1>
          Find out more
        </h1>
        <p>
          To find out more, as well as see how to work with us, click the boxes below.
        </p>
      </div>
      <ul class="promo--sections__list">
        <li class="promo--sections__list__item promo--sections__list__item--education">
          <a href="education.html">
          <h4>Education</h4>
          </a>
        </li>
        <li class="promo--sections__list__item promo--sections__list__item--developers">
          <a href="developers.html">
          <h4>Product developers</h4>
          </a>
        </li>
      </ul>
  </section>
<?php

page_footer();