<?php /***** Process this file with tools/generate.php to produce HTML *****/

page_header('Guides');

?>
		<section>
			<dl>
				<dt><a href="/inside-acropolis/">Inside Acropolis</a></dt>
				<dd>A guide to the Research and Education Space for contributors and developers</dd>
			</dl>
			<dl>
				<dt><a href="/painting-by-numbers/">Painting by Numbers</a></dt>
				<dd>The visual style &amp; mark-up guide for the Research and Education Space</dd>
			</dl>
			<dl>
				<dt><a href="/twine/">Twine</a></dt>
				<dd>An introduction to and manual pages for Twine, a modular workflow engine for publishing linked data.</dd>
			</dl>
		</section>
<?php
	
page_footer();
	
?>