<?php /***** Process this file with tools/generate.php to produce HTML *****/

page_header(null, 'home');

?>
		<section class="promo promo-intro">
      <div class="wrapper">   
  			<h1>
  				Welcome to the Research and Education Space (RES) – an initiative to promote access to public archives for use in education.
  			</h1>
  			<p>
  				Over four years the RES project is working with teachers, students and academics, as well as with collection holders and product developers to improve the resources and the tools available in education. RES is a partnership between <a href="https://www.jisc.ac.uk/">Jisc</a>, the <a href="http://bufvc.ac.uk/">British Universities Film &amp; Video Council (BUFVC)</a> and the BBC. 
  			</p>
      </div>
		</section>
  	<section class="promo promo--sections">
      <div class="wrapper">      
        <h1>
          Find out more
        </h1>
        <p>
          To find out more, as well as see how to work with us, click the boxes below.
        </p>
      </div>
      <ul class="promo--sections__list">
        <li class="promo--sections__list__item promo--sections__list__item--education">
          <a href="/res/education">
          <h4>Education</h4>
          </a>
        </li>
        <li class="promo--sections__list__item promo--sections__list__item--collection">
          <a href="/res/collection">
          <h4>Collection holders</h4>
          </a>
        </li>
        <li class="promo--sections__list__item promo--sections__list__item--developers">
          <a href="/res/developers">
          <h4>Product developers</h4>
          </a>
        </li>
      </ul>
		</section>
    <section class="promo promo--tech">
      <div class="wrapper">
        <h1>Trusted and permanently available</h1>
        <p>
          You will find guidance and documentation for application developers, data contributors and users of RES in Technology. RES offers a free, open-source, openly licenced index of cultural assets from some of the world's leading cultural institutions. Images, video, TV and radio programmes, podcasts, text, pre-formatted teaching materials, all are being indexed by RES. Plug RES into your product and you will instantly add value to your clients and hence to your product.
        </p>
        <p><a class="promo--tech__btn" href="/res/tech"><span>Technical guides</span></a></p>
      </div>
    </section>
<?php

page_footer();
