<?php /***** Process this file with tools/generate.php to produce HTML *****/

page_header(null, 'home', true);

?>
		<section class="promo promo-intro">
      <div class="wrapper">   
  			<h1>
  				Welcome to the Research and Education Space (RES) – an initiative to promote access to public archives for use in education.
  			</h1>
  			<p>
  				Since 2012, the RES project has been working with teachers, students and academics, as well as with collection holders and product developers to improve the resources and the tools available in all levels of UK education.  RES is a partnership between <a href="https://www.jisc.ac.uk/">Jisc</a>, the <a href="http://bufvc.ac.uk/">British Universities Film &amp; Video Council (BUFVC)</a> and the <a href="https://www.bbc.co.uk/">BBC</a>. 
  			</p>
      </div>
		</section>
  	<section class="promo promo--sections">
      <ul class="promo--sections__list">
        <li class="promo--sections__list__item promo--sections__list__item--education">
          <a class="promo--sections__link" href="/res/education">
            <div class="promo--sections__link__inner">
              <h4>Education</h4>
              <p>Lorem ipsum sit amet consecuter</p>
            </div>
          </a>
        </li>
        <li class="promo--sections__list__item promo--sections__list__item--collection">
          <a class="promo--sections__link" href="/res/collections">
            <div class="promo--sections__link__inner">
              <h4>Collections</h4>
              <p>Lorem ipsum sit amet consecuter</p>
            </div>
          </a>
        </li>
        <li class="promo--sections__list__item promo--sections__list__item--developers">
          <a class="promo--sections__link" href="/res/products">
            <div class="promo--sections__link__inner">
              <h4>Products</h4>
              <p>Lorem ipsum sit amet consecuter</p>
            </div>
          </a>
        </li>
      </ul>
		</section>
    <section class="promo promo--tech">
      <div class="wrapper">
        <h1>Trusted and permanently available</h1>
        <p>
          The BBC has built an open platform which indexes and organises the catalogues of many of our libraries, museums, broadcasters and galleries and the assets they describe, including documents, images, TV and radio programmes. Developers can then incorporate or build products on the RES platform to provide access to these collections via educational tools.
        </p>
        <p><a class="promo--tech__btn" href="/res/developers"><span>Developer resources</span></a></p>
      </div>
    </section>
<?php

page_footer();
