<?php /***** Process this file with tools/generate.php to produce HTML *****/

page_header(null, 'home tech');

?>

    <section class="keynav">
      <div class="inner">
        <dl class="item" id="guides">
          <dt><a href="/res/guides"><span class="icon"></span>Guides</a></dt>
          <dd>
            Guidance and documentation for application developers,
            data contributors, and users of RES tools.
          </dd>
        </dl>       
        <dl class="item" id="api">
          <dt><a href="http://acropolis.org.uk/"><span class="icon"></span>Developer API</a></dt>
          <dd>
            The RES platform provides a Linked Open Data API
            so that developers can build applications against the
            RES index.
          </dd>
        </dl>
        <dl class="item" id="tools">
          <dt><a href="/res/tools"><span class="icon"></span>Tools</a></dt>
          <dd>
            As well as developing and operating an indexing platform,
            the RES project is creating and releasing tools and
            utilities in order to assist contributors in publishing
            their data.
          </dd>
        </dl>
      </div>
    </section>
<?php

page_footer();
