<?php /***** Process this file with tools/generate.php to produce HTML *****/

page_header('Tools', 'tech-tools', null, true);

?>
		<section id="twine">
			<h1><a href="/twine/">Twine</a></h1>
			<p>
				Twine is a modular, queue-driven workflow engine for publishing linked open data.
			</p>
			<p>
				Twine receives messages via the <a href="http://www.amqp.org">AMQP</a> message queue protocol,
				processes them (translating to RDF), and pushes them into a store using
				<a href="http://www.w3.org/TR/sparql11-overview/">SPARQL</a>.
			</p>
			<p>
				Although Twine includes some XSLT-based transformation capability out of the box,
				the intention is that users of Twine will develop their own processing modules to
				suit their particular workflows.
			</p>
		</section>
		<section id="quilt">
			<h1><a href="https://github.com/bbcarchdev/quilt">Quilt</a></h1>
			<p>
				Quilt is a modular front-end for publishing Linked Open Data.
			</p>
			<p>
				Quilt powers the API of the Research &amp; Education Space, as well
				as endpoints where we are <a href="#data">publishing data ourselves</a>.
				It is implemented primarily as a <a href="http://www.fastcgi.com/">FastCGI</a>
				applications (and so can be used with various different web servers) and
				includes engines for generating pages based upon graph queries from
				SPARQL servers and serving the contents of Turtle files in a directory.
			</p>
			<p>
				Quilt itself performs content negotiation and will serve the various
				serialisations supported by <a href="http://librdf.org">librdf</a>. A plug-in
				module included in the source tree, and used by the Research &amp; Education
				Space, allows HTML to generated based upon a subset of the
				<a href="http://liquidmarkup.org">Liquid</a> templating language.
			</p>
		</section>
		<section id="chrome-lod">
			<h1><a href="https://github.com/bbcarchdev/chrome-lod">Linked Open Data extension for Chrome</a></h1>
			<p>
				This is an extension for Google Chrome that looks for the
				presence of Linked Open Data behind the pages that you browse
				and reveals it if available.
			</p>
			<p>
				Note that currently this must be installed as an
				<a href="https://developer.chrome.com/extensions/getstarted#unpacked">“unpacked extension”</a> using Chrome’s developer mode.
			</p>
		</section>
		<section id="data">
			<h1>Datasets</h1>
			<p>
				As part of our development of the Research &amp; Education Space, we
				are also publishing some <a href="http://opendefinition.org/od/">Open Data</a>,
				which will be incorporated into the platform.
			</p>
			<h2><a href="http://billings.acropolis.org.uk/">BBC Broadcast Billings Data</a></h2>
			<p>
				This dataset publishes information about BBC broadcasts shortly after
				they end, as Linked Open Data. The dataset currently has coverage
				back to 2007. Over time we hope to extend both the services and the time
				period covered.
			</p>
			<p>
				This set has been published primarily to ensure that the Research &amp; Education
				Space includes information about these programmes, and can collate information
				about where playable versions of them can be accessed and by whom.
			</p>
			<p>
				This dataset does not contain a great deal of descriptive metadata (such as synopses,
				genres and subject classifications), but does include technical metadata
				about broadcasts and, where it can be included, mappings to identifiers for programmes
				and services from other data sources.
			</p>
		</section>
<?php
	
page_footer();
	
?>